export const data = [
  {
    name: "Persimmon",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Gooseberry.jpeg?alt=media&token=989c94dd-f99e-47bf-8350-3dcd113834b0",
    id: 52,
    family: "Ebenaceae",
    order: "Rosales",
    genus: "Diospyros",
    nutritions: {
      calories: 81,
      fat: 0,
      sugar: 18,
      carbohydrates: 18,
      protein: 0,
    },
  },
  {
    name: "Strawberry",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/pexels-ave-calvar-martinez-6944172.jpg?alt=media&token=2dc13543-69ee-4972-95d3-699df58d06de",
    id: 3,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Fragaria",
    nutritions: {
      calories: 29,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0.8,
    },
  },
  {
    name: "Banana",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/pexels-kio-1093038.jpg?alt=media&token=5c2addb9-8abb-44ac-b70c-78f639fd1296",
    id: 1,
    family: "Musaceae",
    order: "Zingiberales",
    genus: "Musa",
    nutritions: {
      calories: 96,
      fat: 0.2,
      sugar: 17.2,
      carbohydrates: 22,
      protein: 1,
    },
  },

  {
    name: "Pear",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/benefits-of-pears-1296x728-feature.webp?alt=media&token=361519a1-271f-464f-88a8-b1ded05578a5",
    id: 4,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Pyrus",
    nutritions: {
      calories: 57,
      fat: 0.1,
      sugar: 10,
      carbohydrates: 15,
      protein: 0.4,
    },
  },
  {
    name: "Durian",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/GettyImages-931749726-920x518.jpg?alt=media&token=71a90c00-26b0-4eef-af6a-01d2de9208ac",
    id: 60,
    family: "Malvaceae",
    order: "Malvales",
    genus: "Durio",
    nutritions: {
      calories: 147,
      fat: 5.3,
      sugar: 6.75,
      carbohydrates: 27.1,
      protein: 1.5,
    },
  },
  {
    name: "Blackberry",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Blackberry.jpeg?alt=media&token=7b6d94bf-36b5-48e8-844a-8f266be69fd3",
    id: 64,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    nutritions: {
      calories: 40,
      fat: 0.4,
      sugar: 4.5,
      carbohydrates: 9,
      protein: 1.3,
    },
  },
  {
    name: "Lingonberry",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Lingonberry.jpeg?alt=media&token=f05cd35f-adac-4b93-a585-0cd7c2b770a0",
    id: 65,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    nutritions: {
      calories: 50,
      fat: 0.34,
      sugar: 5.74,
      carbohydrates: 11.3,
      protein: 0.75,
    },
  },
  {
    name: "Kiwi",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Kiwi.jpeg?alt=media&token=2eb01e8a-5fe4-424f-9062-e61ed94b5117",
    id: 66,
    family: "Actinidiaceae",
    order: "Struthioniformes",
    genus: "Apteryx",
    nutritions: {
      calories: 61,
      fat: 0.5,
      sugar: 9,
      carbohydrates: 15,
      protein: 1.1,
    },
  },

  {
    name: "Pineapple",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Pineapple.jpeg?alt=media&token=e486da31-3ccc-41e0-ab55-b2fcd27821bb",
    id: 10,
    family: "Bromeliaceae",
    order: "Poales",
    genus: "Ananas",
    nutritions: {
      calories: 50,
      fat: 0.12,
      sugar: 9.85,
      carbohydrates: 13.12,
      protein: 0.54,
    },
  },
  {
    name: "Fig",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Fig.jpeg?alt=media&token=4e896259-0860-43c1-aebe-31b5a25a317f",
    id: 68,
    family: "Moraceae",
    order: "Rosales",
    genus: "Ficus",
    nutritions: {
      calories: 74,
      fat: 0.3,
      sugar: 16,
      carbohydrates: 19,
      protein: 0.8,
    },
  },
  {
    name: "Gooseberry",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Gooseberry.jpeg?alt=media&token=989c94dd-f99e-47bf-8350-3dcd113834b0",
    id: 69,
    family: "Grossulariaceae",
    order: "Saxifragales",
    genus: "Ribes",
    nutritions: {
      calories: 44,
      fat: 0.6,
      sugar: 0,
      carbohydrates: 10,
      protein: 0.9,
    },
  },

  {
    name: "Plum",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Plum.jpeg?alt=media&token=fc665795-e384-4468-853b-d3ab7896892c",
    id: 71,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    nutritions: {
      calories: 46,
      fat: 0.28,
      sugar: 9.92,
      carbohydrates: 11.4,
      protein: 0.7,
    },
  },
  {
    name: "Orange",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Orange.jpeg?alt=media&token=6075ecc4-91e6-43d3-879d-2b65e949079c",
    id: 2,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    nutritions: {
      calories: 43,
      fat: 0.2,
      sugar: 8.2,
      carbohydrates: 8.3,
      protein: 1,
    },
  },
  {
    name: "GreenApple",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/GreenApple.jpeg?alt=media&token=4ebb8e3b-695d-46f7-9457-e77f4852cf62",
    id: 72,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    nutritions: {
      calories: 21,
      fat: 0.1,
      sugar: 6.4,
      carbohydrates: 3.1,
      protein: 0.4,
    },
  },
  {
    name: "Raspberry",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Raspberry.jpeg?alt=media&token=5301f1bc-a78f-4a80-a909-faeb85204128",
    id: 23,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    nutritions: {
      calories: 53,
      fat: 0.7,
      sugar: 4.4,
      carbohydrates: 12,
      protein: 1.2,
    },
  },
  {
    name: "Watermelon",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Watermelon.jpeg?alt=media&token=76dc2354-c662-4a54-8d4b-1c1bc9de17bc",
    id: 25,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Citrullus",
    nutritions: {
      calories: 30,
      fat: 0.2,
      sugar: 6,
      carbohydrates: 8,
      protein: 0.6,
    },
  },
  {
    name: "Mango",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/pexels-julie-aagaard-2294471.jpg?alt=media&token=ccb90462-634e-4bbc-b312-2ccf1e2af0ba",
    id: 27,
    family: "Anacardiaceae",
    order: "Sapindales",
    genus: "Mangifera",
    nutritions: {
      calories: 60,
      fat: 0.38,
      sugar: 13.7,
      carbohydrates: 15,
      protein: 0.82,
    },
  },
  {
    name: "Blueberry",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Blueberry.jpeg?alt=media&token=8d58e21c-8fe7-411a-bffe-7cb11ae12718",
    id: 33,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Fragaria",
    nutritions: {
      calories: 29,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0,
    },
  },
  {
    name: "Apple",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/pexels-pixabay-209439.jpg?alt=media&token=beadee0e-c749-45ea-a1ae-529e6626db86",
    id: 6,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    nutritions: {
      calories: 52,
      fat: 0.4,
      sugar: 10.3,
      carbohydrates: 11.4,
      protein: 0.3,
    },
  },
  {
    name: "Guava",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Guava.jpeg?alt=media&token=093a609d-c527-4840-afc7-b81fe9707340",
    id: 37,
    family: "Myrtaceae",
    order: "Myrtales",
    genus: "Psidium",
    nutritions: {
      calories: 68,
      fat: 1,
      sugar: 9,
      carbohydrates: 14,
      protein: 2.6,
    },
  },
  {
    name: "Apricot",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Apricot.jpeg?alt=media&token=bcad8384-b7eb-419a-879f-1d840c879039",
    id: 35,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    nutritions: {
      calories: 15,
      fat: 0.1,
      sugar: 3.2,
      carbohydrates: 3.9,
      protein: 0.5,
    },
  },
  {
    name: "Papaya",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Papaya.webp?alt=media&token=19294838-3349-4f81-a1d8-4530ed80005f",
    id: 42,
    family: "Caricaceae",
    order: "Caricacea",
    genus: "Carica",
    nutritions: {
      calories: 43,
      fat: 0.4,
      sugar: 1,
      carbohydrates: 11,
      protein: 0,
    },
  },
  {
    name: "Melon",
    id: 41,
    family: "Cucurbitaceae",
    order: "Cucurbitaceae",
    genus: "Cucumis",
    nutritions: {
      calories: 34,
      fat: 0,
      sugar: 8,
      carbohydrates: 8,
      protein: 0,
    },
  },
  {
    name: "Tangerine",
    id: 77,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    nutritions: {
      calories: 45,
      fat: 0.4,
      sugar: 9.1,
      carbohydrates: 8.3,
      protein: 0,
    },
  },
  {
    name: "Pitahaya",
    id: 78,
    family: "Cactaceae",
    order: "Caryophyllales",
    genus: "Cactaceae",
    nutritions: {
      calories: 36,
      fat: 0.4,
      sugar: 3,
      carbohydrates: 7,
      protein: 1,
    },
  },
  {
    name: "Lime",
    id: 44,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    nutritions: {
      calories: 25,
      fat: 0.1,
      sugar: 1.7,
      carbohydrates: 8.4,
      protein: 0.3,
    },
  },
  {
    name: "Pomegranate",
    id: 79,
    family: "Lythraceae",
    order: "Myrtales",
    genus: "Punica",
    nutritions: {
      calories: 83,
      fat: 1.2,
      sugar: 13.7,
      carbohydrates: 18.7,
      protein: 1.7,
    },
  },
  {
    name: "Dragonfruit",
    id: 80,
    family: "Cactaceae",
    order: "Caryophyllales",
    genus: "Selenicereus",
    nutritions: {
      calories: 60,
      fat: 1.5,
      sugar: 8,
      carbohydrates: 9,
      protein: 9,
    },
  },
  {
    name: "Grape",
    id: 81,
    family: "Vitaceae",
    order: "Vitales",
    genus: "Vitis",
    nutritions: {
      calories: 69,
      fat: 0.16,
      sugar: 16,
      carbohydrates: 18.1,
      protein: 0.72,
    },
  },
  {
    name: "Morus",
    id: 82,
    family: "Moraceae",
    order: "Rosales",
    genus: "Morus",
    nutritions: {
      calories: 43,
      fat: 0.39,
      sugar: 8.1,
      carbohydrates: 9.8,
      protein: 1.44,
    },
  },
  {
    name: "Feijoa",
    id: 76,
    family: "Myrtaceae",
    order: "Myrtoideae",
    genus: "Sellowiana",
    nutritions: {
      calories: 44,
      fat: 0.4,
      sugar: 3,
      carbohydrates: 8,
      protein: 0.6,
    },
  },
  {
    name: "Avocado",
    id: 84,
    family: "Lauraceae",
    order: "Laurales",
    genus: "Persea",
    nutritions: {
      calories: 160,
      fat: 14.66,
      sugar: 0.66,
      carbohydrates: 8.53,
      protein: 2,
    },
  },
  {
    name: "Kiwifruit",
    img: "https://firebasestorage.googleapis.com/v0/b/socail-meda.appspot.com/o/Kiwi.jpeg?alt=media&token=2eb01e8a-5fe4-424f-9062-e61ed94b5117",
    id: 85,
    family: "Actinidiaceae",
    order: "Ericales",
    genus: "Actinidia",
    nutritions: {
      calories: 61,
      fat: 0.5,
      sugar: 8.9,
      carbohydrates: 14.6,
      protein: 1.14,
    },
  },
  {
    name: "Cranberry",
    id: 87,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    nutritions: {
      calories: 46,
      fat: 0.1,
      sugar: 4,
      carbohydrates: 12.2,
      protein: 0.4,
    },
  },
  {
    name: "Cherry",
    id: 9,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    nutritions: {
      calories: 50,
      fat: 0.3,
      sugar: 8,
      carbohydrates: 12,
      protein: 1,
    },
  },
  {
    name: "Peach",
    id: 86,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    nutritions: {
      calories: 39,
      fat: 0.25,
      sugar: 8.4,
      carbohydrates: 9.5,
      protein: 0.9,
    },
  },
  {
    name: "Jackfruit",
    id: 94,
    family: "Moraceae",
    order: "Rosales",
    genus: "Artocarpus",
    nutritions: {
      calories: 95,
      fat: 0,
      sugar: 19.1,
      carbohydrates: 23.2,
      protein: 1.72,
    },
  },
  {
    name: "Horned Melon",
    id: 95,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Cucumis",
    nutritions: {
      calories: 44,
      fat: 1.26,
      sugar: 0.5,
      carbohydrates: 7.56,
      protein: 1.78,
    },
  },
];
